### ISSUE TITLE
:bug: Flutter bug launch screen layout broken..

### ISSUE THREAD

**Issue by koutalou** [splathon/splathon-client#4]
Flutterの問題ぽいけどデザイン指定の起動画面だとバグる・・

![broken_launch](https://user-images.githubusercontent.com/1267315/55975879-deee9080-5cc5-11e9-9729-67a137494689.gif)

Same problem: https://github.com/flutter/flutter/issues/30592

**Comment by koutalou** [comment]
SafeAreaでAutolayout実装するとバグるってところまでは特定できた、古くからのSuperView指定でのAutolayoutであればなぜかバグらなかったのでそれでおkとする

**Comment by koutalou** [comment]
Fixed iPhoneXR

<img src="https://user-images.githubusercontent.com/1267315/55977111-ec594a00-5cc8-11e9-8783-66f56d32d74a.png" width="300px">

**Comment by alvinthen** [comment]
Fixed? Like how?
