### ISSUE TITLE
お知らせの最後のSeparate borderが一部重なる

### ISSUE THREAD

**Issue by koutalou** [splathon/splathon-client#6]
## What

重なるというか実装上しょうがなく意図して実装している
何とか最後のListのSeparate部を重複しないようにしたい

## Problem Code

https://github.com/splathon/splathon-client/blob/master/lib/views/notification.dart#L160

一番上は全てのBorder, それ以降Topを除くBorderを引く実装にしている
最後の部分だけど角丸処理のためRadius実装しているのだが、どうやらFlutterの不具合というか動作仕様？で `Border.all()` のBorderじゃないと角丸にならずBorderが全部非表示になってしまうっぽい。
その制限のせいで最後のListも `Border.all()` で実装している

ちなみに `BorderSide` で4辺全てのBorderを実装してもうまく角丸にならず全て非表示になる（オワコン

## Screenshot

<img src="https://user-images.githubusercontent.com/1267315/56091883-81d62300-5eef-11e9-81ba-5293fa2d2673.png" width="300px">

**Comment by meguu** [comment]
もう試したかもしれないですが、丸角のBoxDecorationの中にListViewを入れるかTextViewを並べて、separatorで区切るのは上手くいかないのでしょうか？

**Comment by koutalou** [comment]
実は以前はその実装で問題なかったのですが、ListView in ListViewになる関係で内部のListView（今回のTarget）はスクロール無効化&HeightをFixedさせて計算しないといけないんですけど、通知内容無制限化してしまった影響でHeight計算が難しくて詰まってしまった状態です（複雑ぅ！

**Comment by meguu** [comment]
あああーー…なるほど、”次の試合はここだ！”が必要だからですか…

**Comment by koutalou** [comment]
このBorderの不具合、まだ直ってないようだ。
しかしデータが2つの時以外は表示不正が起きないように直した。

この不具合は所詮…先の時代の敗北者じゃけェ…!!

Fixed: https://github.com/splathon/splathon-client/commit/daeeb6115f32f16952b40316198e56a2582db7ea
