### ISSUE TITLE
タブ移動時にRefetchしてる

### ISSUE THREAD

**Issue by koutalou** [splathon/splathon-client#8]
## what

* タブ移動(上下問わず)するたびに、Refetch処理が走ってる
* ちゃんとDocument読んでなくてライフサイクルの処理がどこかおかしいかも
  * modelとして扱ってるプロパティがタブ移動でnullになってるかもしれない

**Comment by meguu** [comment]
state管理に、AutomaticKeepAliveClientMixinを使うと良さそうです。
https://api.flutter.dev/flutter/widgets/AutomaticKeepAliveClientMixin-mixin.html

こちら、仮にRefetchしないようにしたとき、ユーザーがRefetchしたいとき（試合内容更新したり）はどうするのかアイディアありますか？(Zeplinにはスペックがあるのでしょうか？）

**Comment by koutalou** [comment]
直ったー！Thank you！
https://github.com/splathon/splathon-client/commit/13dc74d84014f29ad7c14bb73d6dc4b6aa9d51a5
